### ISSUE TITLE
일부 영역 스크롤 제한

### ISSUE THREAD

**Issue by bohyunjung** [undersalon/gyugle_coding_jam#1]
마우스 커서를 아래 빨간 표시된 영역에 두고 스크롤을 하면 먹지 않는 현상이 발생합니다.
`fixed` 속성의 배경그래픽 영역을 hover하기 때문인 것 같습니다.
아래 scroll 되어야 하는 Home 영역의 속성을 `top: 750px`에서 `padding-top: 750px`로 바꾸어, 해당 영역이 scroll에 잡히도록 수정해 PR 올리겠습니다. 검토 후 반영 부탁드립니다.

![2018-05-28 00 05 05](https://user-images.githubusercontent.com/8598722/40587542-493529e2-620b-11e8-8a5b-ae91c5ab5c7b.png)

**Comment by firekim2** [comment]
오
